package

  # hide from PAUSE
  Test::Baruwa::Scanner;

use strict;
use warnings;
use File::Touch;
use File::NCopy;
use FindBin '$Bin';
use File::Path qw(make_path remove_tree);
use Exporter qw/import/;

our @EXPORT = qw/create_config make_test_dirs create_file/;

my @paths = (
    "$Bin/data/var/run/baruwa/scanner",
    "$Bin/data/var/spool/baruwa/incoming",
    "$Bin/data/var/spool/baruwa/quarantine",
    "$Bin/data/var/spool/exim/input",
    "$Bin/data/var/spool/exim.in/input",
    "$Bin/data/var/lock/Baruwa",
    "$Bin/data/etc/mail/baruwa/dynamic/rules",
    "$Bin/data/etc/mail/baruwa/dynamic/signatures",
);
my @files = ("$Bin/data/var/lock/Baruwa/test-lock");
our @msgs = ('1bUUOQ-0000g4-C7', '1bUvRz-0001Mr-4W', '1bVCqk-0001rd-7G');

my $header1 = <<'HEADER1';
1bUUOQ-0000g4-C7-H
exim 93 93
<andrew@kudusoft.home.topdog-software.com>
1470123938 0
-helo_name fuzzylumpkins.home.topdog-software.com
-host_address 192.168.1.52.62765
-host_name fuzzylumpkins.home.topdog-software.com
-interface_address 192.168.1.14.25
-active_hostname ms2.home.topdog-software.com
-received_protocol esmtps
-aclc _n 1
0
-aclc _l 3
250
-aclm _av_scanner 32
clamd:/var/run/clamav/clamd.sock
-aclm 0 2
no
-body_linecount 2
-max_received_linelength 56
-tls_cipher TLS1.2:ECDHE_RSA_AES_256_GCM_SHA384:256
-tls_ourcert -----BEGIN CERTIFICATE-----\nMIIGRjCCBS6gAwIBAgISAyaEr1dYsVd/bDUKfZmQByDFMA0GCSqGSIb3DQEBCwUA\nMEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD\nExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0xNjA2MTgxNjAwMDBaFw0x\nNjA5MTYxNjAwMDBaMCoxKDAmBgNVBAMTH3NjYW5uZXIubGFiLnRvcGRvZy1zb2Z0\nd2FyZS5jb20wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCu9Xl/A28t\n3TeU/NkVQtAlioDOtEPqkOdslKviiKS/saQItq1ojlX/ohb37v+aW/74EiW2IjYd\nQwXa2sI1XjwLCHJ3PGQVpxMGhvvFW5lLfsBEi4lqjQdaIt7G/ZN3oAMJf078Hs28\nVMjKPvMx1HxwFmxcdeTwpjBOXa4F4/HqLcRp8JrOcwBbZMgQQxfZagfpmQ4XKMsC\nrXAL16KT6x+T0cLDxtLo32mc75hQZ1UhutWRNFI7O151pgS+cdNR77Y/FiRcfQ8y\nqz4NNIMQEuSy8UPtlHgw+mHrpjnYmuHf8ogchJMb3ZvdsQUX+xFL5a/VVtuMTYmk\nFdx7V0Guz7Y1YUzVDU9tsz96G0V3y0UaIOgAPUabBvUnsyhQ40Js7nR+/BZ34uzx\nFBLp9BSA5zhc3shslUN7WrV+3v9462mYKTrdjH3qwyaeh9d8HNM39O2yJmkkJvv/\npwevbLvqIRN3vCCBmlFi8qsgwOG08Zm/yiDOzFg5BjZVXw6ADI7sMUqlvxZx5whM\nOHnr1ua/GNpHRwTeXkGuQtvFAjqPmQAXZeSQTNuUpNrclosgEvgpJchAKnkqBRFd\nXpKqGbKlp8UQYg0AQJiIipXc06ZHiIrZQ4g+3cbr7uQUrkuFxti4bo4fpXOj4P6M\nkXfPnoAGqx+dpv85ZEMkLpCjVr3/hxzoLQIDAQABo4ICRDCCAkAwDgYDVR0PAQH/\nBAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8E\nAjAAMB0GA1UdDgQWBBR7b9MfNDC6QGMCDOdpv7W0QVUskjAfBgNVHSMEGDAWgBSo\nSmpjBH3duubRObemRWXv86jsoTBwBggrBgEFBQcBAQRkMGIwLwYIKwYBBQUHMAGG\nI2h0dHA6Ly9vY3NwLmludC14My5sZXRzZW5jcnlwdC5vcmcvMC8GCCsGAQUFBzAC\nhiNodHRwOi8vY2VydC5pbnQteDMubGV0c2VuY3J5cHQub3JnLzBOBgNVHREERzBF\ngiJwb3N0b2ZmaWNlLmxhYi50b3Bkb2ctc29mdHdhcmUuY29tgh9zY2FubmVyLmxh\nYi50b3Bkb2ctc29mdHdhcmUuY29tMIH+BgNVHSAEgfYwgfMwCAYGZ4EMAQIBMIHm\nBgsrBgEEAYLfEwEBATCB1jAmBggrBgEFBQcCARYaaHR0cDovL2Nwcy5sZXRzZW5j\ncnlwdC5vcmcwgasGCCsGAQUFBwICMIGeDIGbVGhpcyBDZXJ0aWZpY2F0ZSBtYXkg\nb25seSBiZSByZWxpZWQgdXBvbiBieSBSZWx5aW5nIFBhcnRpZXMgYW5kIG9ubHkg\naW4gYWNjb3JkYW5jZSB3aXRoIHRoZSBDZXJ0aWZpY2F0ZSBQb2xpY3kgZm91bmQg\nYXQgaHR0cHM6Ly9sZXRzZW5jcnlwdC5vcmcvcmVwb3NpdG9yeS8wDQYJKoZIhvcN\nAQELBQADggEBAC3CFdwbBbVbGGh4Lga1yF8GDVkkjE7twQmJI0oWfjX87J4axJIG\neLK+DGdI0ZuknpwsxxA6CBIdibS6X9beEOYaOHza8WLz7GW2zX2u5RuOuBq6bpkd\nvxA8iBdWPY63DH4tYVceo8dqmCrlbHtEA99pesvUcH3Uy2IlvlVRjdSk9t0m9+em\nMWeF9gOwYxgdPys3QUayfBzK/x+lltJjxisibtUbou2AYDTIiMCxjrRTyiYYctNR\nTRdVKV0nOjjgvsscIkFBKP6iwmzyH6DgOTsfkzZkTqlOVU0rrBMlWXlqmd+3Be1Q\nIzRqELgGN2T7+j8cY9mgKyYhzZ3GrH7HIac=\n-----END CERTIFICATE-----\n
XX
1
andrew@home.topdog-software.com

342P Received: from fuzzylumpkins.home.topdog-software.com ([192.168.1.52])
    by postoffice.lab.topdog-software.com with esmtps (TLS1.2:ECDHE_RSA_AES_256_GCM_SHA384:256)
    (Baruwa 2.0)
    (envelope-from <andrew@kudusoft.home.topdog-software.com>)
    id 1bUUOQ-0000g4-C7 ret-id none;
    for andrew@home.topdog-software.com; Tue, 02 Aug 2016 09:45:38 +0200
038  Date: Tue, 02 Aug 2016 09:45:39 +0200
036T To: andrew@home.topdog-software.com
047F From: andrew@kudusoft.home.topdog-software.com
046  Subject: test Tue, 02 Aug 2016 09:45:39 +0200
057  X-Mailer: swaks v20130209.0 jetmore.org/john/code/swaks/
049  X-Baruwa-Virus-Checks: bypassed smtp time checks
HEADER1

my $body1 = <<'BODY1';
1bUUOQ-0000g4-C7-D
This is a test mailing
BODY1

my $header2 = <<'HEADER2';
1bUvRz-0001Mr-4W-H
exim 93 93
<andrew@home.topdog-software.com>
1470227947 0
-helo_name fuzzylumpkins.home.topdog-software.com
-host_address 192.168.1.52.65531
-interface_address 192.168.1.14.25
-active_hostname ms2.home.topdog-software.com
-received_protocol esmtps
-aclc _n 1
0
-aclc _l 3
250
-aclm _av_scanner 32
clamd:/var/run/clamav/clamd.sock
-aclm 0 2
no
-body_linecount 347
-max_received_linelength 76
-host_lookup_failed
-tls_cipher TLS1.2:ECDHE_RSA_AES_256_GCM_SHA384:256
-tls_ourcert -----BEGIN CERTIFICATE-----\nMIIGRjCCBS6gAwIBAgISAyaEr1dYsVd/bDUKfZmQByDFMA0GCSqGSIb3DQEBCwUA\nMEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD\nExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0xNjA2MTgxNjAwMDBaFw0x\nNjA5MTYxNjAwMDBaMCoxKDAmBgNVBAMTH3NjYW5uZXIubGFiLnRvcGRvZy1zb2Z0\nd2FyZS5jb20wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCu9Xl/A28t\n3TeU/NkVQtAlioDOtEPqkOdslKviiKS/saQItq1ojlX/ohb37v+aW/74EiW2IjYd\nQwXa2sI1XjwLCHJ3PGQVpxMGhvvFW5lLfsBEi4lqjQdaIt7G/ZN3oAMJf078Hs28\nVMjKPvMx1HxwFmxcdeTwpjBOXa4F4/HqLcRp8JrOcwBbZMgQQxfZagfpmQ4XKMsC\nrXAL16KT6x+T0cLDxtLo32mc75hQZ1UhutWRNFI7O151pgS+cdNR77Y/FiRcfQ8y\nqz4NNIMQEuSy8UPtlHgw+mHrpjnYmuHf8ogchJMb3ZvdsQUX+xFL5a/VVtuMTYmk\nFdx7V0Guz7Y1YUzVDU9tsz96G0V3y0UaIOgAPUabBvUnsyhQ40Js7nR+/BZ34uzx\nFBLp9BSA5zhc3shslUN7WrV+3v9462mYKTrdjH3qwyaeh9d8HNM39O2yJmkkJvv/\npwevbLvqIRN3vCCBmlFi8qsgwOG08Zm/yiDOzFg5BjZVXw6ADI7sMUqlvxZx5whM\nOHnr1ua/GNpHRwTeXkGuQtvFAjqPmQAXZeSQTNuUpNrclosgEvgpJchAKnkqBRFd\nXpKqGbKlp8UQYg0AQJiIipXc06ZHiIrZQ4g+3cbr7uQUrkuFxti4bo4fpXOj4P6M\nkXfPnoAGqx+dpv85ZEMkLpCjVr3/hxzoLQIDAQABo4ICRDCCAkAwDgYDVR0PAQH/\nBAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8E\nAjAAMB0GA1UdDgQWBBR7b9MfNDC6QGMCDOdpv7W0QVUskjAfBgNVHSMEGDAWgBSo\nSmpjBH3duubRObemRWXv86jsoTBwBggrBgEFBQcBAQRkMGIwLwYIKwYBBQUHMAGG\nI2h0dHA6Ly9vY3NwLmludC14My5sZXRzZW5jcnlwdC5vcmcvMC8GCCsGAQUFBzAC\nhiNodHRwOi8vY2VydC5pbnQteDMubGV0c2VuY3J5cHQub3JnLzBOBgNVHREERzBF\ngiJwb3N0b2ZmaWNlLmxhYi50b3Bkb2ctc29mdHdhcmUuY29tgh9zY2FubmVyLmxh\nYi50b3Bkb2ctc29mdHdhcmUuY29tMIH+BgNVHSAEgfYwgfMwCAYGZ4EMAQIBMIHm\nBgsrBgEEAYLfEwEBATCB1jAmBggrBgEFBQcCARYaaHR0cDovL2Nwcy5sZXRzZW5j\ncnlwdC5vcmcwgasGCCsGAQUFBwICMIGeDIGbVGhpcyBDZXJ0aWZpY2F0ZSBtYXkg\nb25seSBiZSByZWxpZWQgdXBvbiBieSBSZWx5aW5nIFBhcnRpZXMgYW5kIG9ubHkg\naW4gYWNjb3JkYW5jZSB3aXRoIHRoZSBDZXJ0aWZpY2F0ZSBQb2xpY3kgZm91bmQg\nYXQgaHR0cHM6Ly9sZXRzZW5jcnlwdC5vcmcvcmVwb3NpdG9yeS8wDQYJKoZIhvcN\nAQELBQADggEBAC3CFdwbBbVbGGh4Lga1yF8GDVkkjE7twQmJI0oWfjX87J4axJIG\neLK+DGdI0ZuknpwsxxA6CBIdibS6X9beEOYaOHza8WLz7GW2zX2u5RuOuBq6bpkd\nvxA8iBdWPY63DH4tYVceo8dqmCrlbHtEA99pesvUcH3Uy2IlvlVRjdSk9t0m9+em\nMWeF9gOwYxgdPys3QUayfBzK/x+lltJjxisibtUbou2AYDTIiMCxjrRTyiYYctNR\nTRdVKV0nOjjgvsscIkFBKP6iwmzyH6DgOTsfkzZkTqlOVU0rrBMlWXlqmd+3Be1Q\nIzRqELgGN2T7+j8cY9mgKyYhzZ3GrH7HIac=\n-----END CERTIFICATE-----\n
XX
1
angel@home.topdog-software.com

337P Received: from [192.168.1.52] (helo=fuzzylumpkins.home.topdog-software.com)
    by postoffice.lab.topdog-software.com with esmtps (TLS1.2:ECDHE_RSA_AES_256_GCM_SHA384:256)
    (Baruwa 2.0)
    (envelope-from <andrew@home.topdog-software.com>)
    id 1bUvRz-0001Mr-4W ret-id none;
    for angel@home.topdog-software.com; Wed, 03 Aug 2016 14:39:07 +0200
038  Date: Wed, 03 Aug 2016 14:39:09 +0200
035T To: angel@home.topdog-software.com
038F From: andrew@home.topdog-software.com
046  Subject: test Wed, 03 Aug 2016 14:39:09 +0200
057  X-Mailer: swaks v20130209.0 jetmore.org/john/code/swaks/
018  MIME-Version: 1.0
072  Content-Type: multipart/mixed; boundary="----=_MIME_BOUNDARY_000_94493"
049  X-Baruwa-Virus-Checks: bypassed smtp time checks
HEADER2

my $body2 = <<'BODY2';
1bUvRz-0001Mr-4W-D
------=_MIME_BOUNDARY_000_94493
Content-Type: text/plain

This is a test mailing
------=_MIME_BOUNDARY_000_94493
Content-Type: application/octet-stream; name="kudzu.doc"
Content-Description: kudzu.doc
Content-Disposition: attachment; filename="kudzu.doc"
Content-Transfer-Encoding: BASE64

0M8R4KGxGuEAAAAAAAAAAAAAAAAAAAAAOwADAP7/CQAGAAAAAAAAAAAAAAABAAAAIgAAAAAAAAAA
EAAAAgAAAAEAAAD+////AAAAAAAAAAD/////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////9
//////////7///8EAAAABQAAAAYAAAAHAAAACAAAAAkAAAAKAAAACwAAAP7///8NAAAADgAAAA8A
AAAQAAAAEQAAABIAAAATAAAAFAAAABUAAAAWAAAAFwAAABgAAAAZAAAAGgAAABsAAAAcAAAAHQAA
AB4AAAAfAAAAIAAAACEAAAD+////IwAAAP7/////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////1IA
bwBvAHQAIABFAG4AdAByAHkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAWAAUA////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
/v///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAD+////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////////////wAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP7///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////
////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/v///wAAAAAAAAAAAQAA
AP7////+////BAAAAAUAAAAGAAAABwAAAAgAAAAJAAAACgAAAAsAAAAMAAAADQAAAA4AAAAPAAAA
EAAAABEAAAASAAAAEwAAABQAAAAVAAAAFgAAABcAAAAYAAAAGQAAABoAAAAbAAAAHAAAAB0AAAAe
AAAAHwAAACAAAAAhAAAAIgAAACMAAAAkAAAAJQAAACYAAAAnAAAAKAAAACkAAAAqAAAAKwAAACwA
AAAtAAAALgAAAC8AAAAwAAAAMQAAADIAAAAzAAAANAAAADUAAAA2AAAANwAAADgAAAA5AAAAOgAA
ADsAAAA8AAAAPQAAAP7///8/AAAAQAAAAEEAAABCAAAA/v///0QAAAD+////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////8BAP7/
AwoAAP////8GCQIAAAAAAMAAAAAAAABGGAAAAE1pY3Jvc29mdCBXb3JkLURva3VtZW50AAoAAABN
U1dvcmREb2MAEAAAAFdvcmQuRG9jdW1lbnQuOAD0ObJxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAEAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAASABwACgABAFsADwACAAAAAAAAAGIAABDx/wIAYgAAAAcARABlAGYA
YQB1AGwAdAAAABEAAAADJABhJAAxJAFBJAAqJAEALwBCKgBPSgIAUUoCAENKFABtSAkIc0gJCFBK
AABeSgAAYUoUAF9IAQR0SAEEbkj/AABIAAEQAQACAEgAAAAJAEgAZQBhAGQAaQBuAGcAIAAxAAAA
HAABAEAmAAomAAtGAQAKJgALRgEAAyQBYSQBBiQBBwBDShwANQgBAFIAAhABAAIAUgAAAAkASABl
AGEAZABpAG4AZwAgADIAAAAmAAIAQCYBCiYBC0YBAAomAQtGAQANxgUAARMLABOkPAAUpDwABiQB
BwBDSg8ANQgBAEYAAxABAAIARgAAAAkASABlAGEAZABpAG4AZwAgADMAAAAWAAMAQCYCCiYCC0YB
AAomAgtGAQAGJAELAG1ICQRzSAkENQgBAAAAAAAAAAAAAAAAAEIAQUDy/6EAQgAAABkAQQBiAHMA
YQB0AHoALQBTAHQAYQBuAGQAYQByAGQAcwBjAGgAcgBpAGYAdABhAHIAdAAAAAAAAAAAAAAAAAA8
AP4f8v/xADwAAAAWAEQAZQBmAGEAdQBsAHQAIABQAGEAcgBhAGcAcgBhAHAAaAAgAEYAbwBuAHQA
AAAAACYAKRDyAAEBJgAAAAsAUABhAGcAZQAgAE4AdQBtAGIAZQByAAAAAABGAP4fAQAiAUYAAAAH
AEgAZQBhAGQAaQBuAGcAAAANABEAE6TwABSkeAAGJAEAGABPSgQAUUoEAENKHABQSgUAXkoGAGFK
HAAuAEIQAQAiAS4AAAAJAFQAZQB4AHQAIABiAG8AZAB5AAAACgASABOkAAAUpHgAAAAgAC8QIQEy
ASAAAAAEAEwAaQBzAHQAAAACABMABABeSgcAQAD+HwEAQgFAAAAABwBDAGEAcAB0AGkAbwBuAAAA
DQAUABOkeAAUpHgADCQBABIAQ0oYADYIAV5KBwBhShgAXQgBJgD+HwEAUgEmAAAABQBJAG4AZABl
AHgAAAAFABUADCQBAAQAXkoHACwAHxABAGIBLAAAAAYASABlAGEAZABlAHIAAAANABYADcYIAAI5
EHIgAQIAAAAsACAQAQByASwAAAAGAEYAbwBvAHQAZQByAAAADQAXAA3GCAACORByIAECAAAAQAD+
HwEAggFAAAAADABCAGEAbABsAG8AbwBuACAAVABlAHgAdAAAAAIAGAAUAE9KCABRSggAQ0oQAF5K
CABhShAANAD+HwEAkgE0AAAADgBUAGEAYgBsAGUAIABDAG8AbgB0AGUAbgB0AHMAAAAFABkADCQB
AAAAPgD+H5EBogE+AAAADQBUAGEAYgBsAGUAIABIAGUAYQBkAGkAbgBnAAAACwAaAAMkAWEkAQwk
AQAGADUIAVwIATAA/h8hAbIBMAAAAA4ARgByAGEAbQBlACAAYwBvAG4AdABlAG4AdABzAAAAAgAb
AAAAAAAAAAMAAAArAAAALAAAAAEAAAAAAAAAAAD/////AgQAAAAAAAABAAAAAAAAAAAA/////wME
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAKwAAACwAAAAAAAAAAAgBAAAAAAgA
AAAAAAAAAAAAlgMAAAQAACoAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AgAAAAIAAAAEAAAABgAAAAgAAAAKAAAAAAgAACoPAAAIAAAAAAgAAOQIAABECQAAIAoAAGgKAADM
CgAAzAsAABoMAAByDAAAIA0AAIYOAADODgAALA8AAAkAAAAKAAAACwAAAAwAAAANAAAADgAAAA8A
AAAQAAAAEQAAABIAAAATAAAAFAAAAA8AAPA4AAAAAAAG8BgAAAAEBAAAAgAAAAMAAAABAAAAAQAA
AAQAAABAAB7xEAAAAAQAAAgBAAAIAgAACPcAABAADwAC8PwBAAAQAAjwCAAAAAMAAAADBAAADwAD
8KABAAAPAATwKAAAAAEACfAQAAAAAAAAAAAAAAABgP//AYD//wIACvAIAAAAAAQAAAUAAAAPAATw
pAAAAKIMCvAIAAAAAgQAAAAKAADDAAvwSAAAAIAAAAABAIEAAAAAAIIAAAAAAIMAAAAAAIQAAAAA
AIgAAAAAAIEB////AIMBAAAAAL8BEAAQAP8BAAAIAIQD98ABAIYD98ABAEMAIvEYAAAAjwMAAAAA
kAMCAAAAkQMAAAAAkgMCAAAAAAAQ8AQAAAAAAAAAAAAR8AQAAAABAAAAAAAN8AQAAAAAAAEADwAE
8LwAAACiDArwCAAAAAMEAAAACgAAAwEL8GAAAACAAAAAAgCBAJdxAQCCAP++AACDAJdxAQCEAP++
AACIAAAAAACBAf///wCDAQAAAAC/ARAAEADAAQAAAADCAf///wDLAc4YAADNAQAAAAD/AQ4ACACE
A/fAAQCGA/fAAQBDACLxGAAAAI8DAAAAAJADAgAAAJEDAAAAAJIDAgAAAAAAEPAEAAAAAAAAAAAA
EfAEAAAAAQAAAAAADfAEAAAAAAACAA8ABPA8AAAAEgAK8AgAAAABBAAAAA4AAEMAC/AYAAAAwAEB
AAAIywEAAAAA/wEIAAgAAQICAAAIAAAR8AQAAAABAAAAAAAAAAMAAACWAwAAAwQAABQAAABd/P//
1w8AABD+//90AAAAAAACBAAAhwAAAJkCAACGAgAAWwQAAHQAAAAAAAEAAQAAAAEAAAD/D/8P/w//
D/8P/w//D/8P/w8AAAEAAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAQAABehLABYIRQ/hXGBQABsAEG
AAABAAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAXoRAAmCEwP0VxgUAAUACBgAAAQAAAP8AAAAA
AAAAAAAAAAAAAAAAAAAAABAAAF6E0AJghDD9FcYFAAHQAgYAAAEAAAD/AAAAAAAAAAAAAAAAAAAA
AAAAAAAQAABehGADYISg/BXGBQABYAMGAAABAAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAXoTw
A2CEEPwVxgUAAfADBgAAAQAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAABAAAF6EgARghID7FcYFAAGA
BAYAAAEAAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAQAABehBAFYITw+hXGBQABEAUGAAABAAAA/wAA
AAAAAAAAAAAAAAAAAAAAAAAAEAAAXoSgBWCEYPoVxgUAAaAFBgAAAQAAAP8AAAAAAAAAAAAAAAAA
AAAAAAAAABAAAF6EMAZghND5FcYFAAEwBgYAAAEAAAABAAAAAAAAAAAAAAAAAAAA////////AQAA
AAAA/0AAAAAAlgMAAAAAAAACEAAAAAAAAACWAwAAUAAACAAAAAAJAAAARxaQAQAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFQAaQBtAGUAcwAgAE4AZQB3ACAAUgBvAG0AYQBuAAAA
NRaQAQIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFMAeQBtAGIAbwBsAAAAMyaQ
AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEEAcgBpAGEAbAAAAEcWkAGAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABUAGkAbQBlAHMAIABOAGUAdwAgAFIAbwBt
AGEAbgAAADMmkAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBAHIAaQBhAGwA
AAAzBpABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQQByAGkAYQBsAAAANQaQ
AYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFQAYQBoAG8AbQBhAAAANQSQAYAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFQAYQBoAG8AbQBhAAAANSaQAQAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFQAYQBoAG8AbQBhAAAAQgAEAAEIjRgAANAC
AABoAQAAAADvsvZm77L2ZgAAAAABAAAAAABzAAAAPgMAAAEAHQAAAAQAg5AdAAAAcwAAAD4DAAAB
AB0AAAAdAAAAAAAAACcDAPAQhAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAS
MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAADwEITf3wMAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP7/AAABAAIAAAAAAAAAAAAAAAAAAAAAAAEA
AADghZ/y+U9oEKuRCAArJ7PZMAAAAOgAAAAKAAAAAQAAAFgAAAACAAAAYAAAAAQAAAB0AAAABwAA
AIgAAAAIAAAAnAAAAAkAAACsAAAACgAAALgAAAALAAAAxAAAAAwAAADQAAAADQAAANwAAAACAAAA
6f0AAB4AAAAMAAAAREVQQVJUTUVOVAkAHgAAAAwAAABQIEMgSm9yZGFhbgAeAAAACwAAAE5vcm1h
bC5kb3QAAB4AAAAIAAAAbGV0c2FldAAeAAAAAgAAADIAAABAAAAAAEbDIwAAAABAAAAAAAAAAAAA
AABAAAAAAEIDVcEwzAFAAAAAAEIDVcEwzAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAA/v8AAAEAAgAAAAAAAAAAAAAAAAAAAAAAAgAAAALVzdWcLhsQk5cIACss+a5EAAAA
BdXN1ZwuGxCTlwgAKyz5rlwAAAAYAAAAAQAAAAEAAAAQAAAAAgAAAOn9AAAYAAAAAQAAAAEAAAAQ
AAAAAgAAAOn9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADspQEBTSAJBAAAABK/
AAAAAAAAMAAAAAAACAAALA8AAA4AQ2FvbGFuODAAAAAAAAAAAAAAAAAAAAAAAAAJBBYAOioAAAAA
AAAAAAAAYAMAAAAAAAAJAAAAAAAAAAAAAAAAAAAALAAAAAAAAAD//w8ACAAAAAEAAAD//w8ACQAA
AAwAAAD//w8AAAAAAAAAAAAAAAAAAAAAAIgAAAAAAGYEAAAAAAAAZgQAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAA2gQAABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AO4EAAA4AAAAJgUAAAwAAAAyBQAAZAAAAAAAAAAAAAAAGgoAAAgCAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9wkAAAIAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiDAAAYgIAAAAA
AAAAAAAABQoAABUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAADbBwAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJYFAABFAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAGYEAABSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbCAAAHgAAANcJAAAYAAAA
uAQAACIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAADvCQAACAAAAAAAAAAAAAAA+QkAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgDZAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgABwAHAAgACwANAEwAQQBC
AE8AVQBSACAAUgBFAFEAVQBJAFMASQBUAEkATwBOACAARgBPAFIATQALACgAVABvACAAYgBlACAA
YwBvAG0AcABsAGUAdABlAGQAIABiAHkAIABMAGkAbgBlACAATQBhAG4AYQBnAGUAcgApAA0ACwAH
AAcAVABPADoAIAAgAEgAdQBtAGEAbgAgAFIAZQBzAG8AdQByAGMAZQBzACAARABlAHAAYQByAHQA
bQBlAG4AdAAHAEYAUgBPAE0AOgAgACAATgBlAHQAdwBvAHIAawAHAAcABwAHAEgATwAgAC8AIABS
AEUARwBJAE8ATgA6ACAAIABOAGUAdAB3AG8AcgBrAAcARABFAFAAQQBSAFQATQBFAE4AVAA6ACAA
TwBwAGUAcgBhAHQAaQBvAG4AcwAHAAcASgBPAEIAIABUAEkAVABMAEUAOgAgAE4ATwBDACAATwBw
AGUAcgBhAHQAbwByAHMABwAHAFMAQQBMAEEAUgBZACAAUwBDAEEATABFADoAIAAgADkAMAAwAAcA
TwBSAEcAQQBOAEkAUwBBAFQASQBPAE4AIABVAE4ASQBUADoAIABOAGUAdAB3AG8AcgBrAAcABwBK
AE8AQgAgAE4AVQBNAEIARQBSADoABwBUAE8AIABDAE8ATQBNAEUATgBDAEUAOgAgADAAMQAvADAA
NwAvADIAMAAxADEABwAHAAcABwBEAEkAVgBJAFMASQBPAE4ABwBOAEEATQBFACAASQBOACAARgBV
AEwATAAHAFMASQBHAE4AQQBUAFUAUgBFACAABwBEAEEAVABFAAcABwBJAE4ASQBUAEkAQQBUAEUA
RAAgAEIAWQA6AAsAKABMAGkAbgBlACAATQBhAG4AYQBnAGUAcgApAAcABwAHAA0ADQAxADkALwAw
ADUALwAyADAAMQAxAAcABwBSAEUAQwBPAE0ATQBFAE4ARABFAEQAIABGAEkAUgBTAFQATABZACAA
QgBZADoAIAALACgASABFAEEARAA6ACAATgBlAHQAdwBvAHIAawAgAE8AcABlAHIAYQB0AGkAbwBu
ACAARABlAHAAYQByAHQAbQBlAG4AdAApAAcABwAHAAcABwBSAEUAQwBPAE0ATQBFAE4ARABFAEQA
IABTAEUAQwBPAE4ARABMAFkAIABCAFkAOgAgAAsAKABMAGkAbgBlACAARwByAG8AdQBwACAARQB4
AGUAYwB1AHQAaQB2AGUAIAAvACAARQB4AGUAYwB1AHQAaQB2AGUAKQAHAAcABwAHAAcAUgBFAEMA
TwBNAE0ARQBOAEQARQBEACAAIABCAFkAOgALACgARQB4AGUAYwB1AHQAaQB2AGUAOgAgAEgAUgAp
AAcABwAHAAcABwAgAEEAUABQAFIATwBWAEEATAA6ACAACwAoAEMAaABpAGUAZgAgAE8AcABlAHIA
YQB0AGkAbgBnACAATwBmAGYAaQBjAGUAcgApAAcABwAHAAcABwAgAEEAUABQAFIATwBWAEEATAA6
ACAACwAoAEMAaABpAGUAZgAgAEYAaQBuAGEAbgBjAGkAYQBsACAATwBmAGYAaQBjAGUAcgApAAcA
BwAHAAcABwBGAEkATgBBAEwAIABBAFAAUABSAE8AVgBBAEwAIABCAFkAOgALACgAQwBoAGkAZQBm
ACAARQB4AGUAYwB1AHQAaQB2AGUAIABPAGYAZgBpAGMAZQByACkABwAHAAcABwAHAE4AQgA6ACAA
IABhACkAIABQAGwAZQBhAHMAZQAgAGEAdAB0AGEAYwBoACAAbQBvAHQAaQB2AGEAdABpAG8AbgAg
AC8AIABqAHUAcwB0AGkAZgBpAGMAYQB0AGkAbwBuACAAYQBzACAAdwBlAGwAbAAgAGEAcwAgAGoA
bwBiACAAbwB1AHQAcAB1AHQAcwAgAGEAbgBkACAAZQBtAHAAbABvAHkAZQBlACAAcwBwAGUAYwBp
AGYAaQBjAGEAdABpAG8AbgBzAC4ACwAJAGIAKQAgAEkAZgAgAGUAbQBwAGwAbwB5AG0AZQBuAHQA
IABpAHMAIAB0AGUAbQBwAG8AcgBhAHIAeQAsACAAcwBwAGUAYwBpAGYAeQAgAHQAaABlACAAcwB0
AGEAcgB0AGkAbgBnACAAYQBuAGQAIABmAGkAbgBpAHMAaABpAG4AZwAgAGQAYQB0AGUAcwAuAAcA
BwANAAcABwBQAEMASgAgABQgIABMAFIARgAtADAAMQAuAEQATwBDACAAMAA1AC8AMgAwADAAOQAN
AA0ADQANAA0ADQANAA0ADQANAEEADQANAFIAZQBjAHIAdQBpAHQAbQBlAG4AdAAgAGEAbgBkACAA
UgBlAHQAZQBuAHQAaQBvAG4AIABEAGUAcABhAHIAdABtAGUAbgB0ACAAIAANAA0ADQANAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAIIAAAGCAAACAgAAAwIAAA8
CAAAgAgAAIQIAACOCAAAxggAAOQIAADoCAAABgkAABYJAAAuCQAARAkAAHgJAACUCQAAoAkAANYJ
AADwCQAAIAoAACQKAAA4CgAAUgoAAGgKAAByCgAArgoAALAKAACyCgAAtAoAALYKAADMCgAA/AoA
AP4KAABKCwAATAsAAE4LAABQCwAAggsAAIQLAADMCwAAzgsAANALAADSCwAA7AsAABYMAAAYDAAA
GgwAABwMAAAgDAAAagwAAGwMAABuDAAAcAwAAHQMAAC+DAAAwAwAAMIMAADEDAAA0AwAACANAAAi
DQAAJA0AACYNAAAyDQAAhg4AAIoOAACMDgAAwA4AACoPAAD6APr29vPv7+/v6+vv6+/r6+vr6+vr
5evv7+Xr4eHh29HK0evh4dHK0evh4eXl6+/v5eXrxMTl5evExOXl68TEvrq3tLcAAAAAAAAABENK
FgAABENKCgAAB0CI/P81CAELQ0oQAECI/P81CAEKNwgBQ0oQADUIAQAMQ0oPAECI/P9eSgIAABJD
Sg8AQIj8/zUIAV5KAgBcCAEAC0NKDwA1CAFhSg8AB0NKCgA1CAELQ0oPAECI/P81CAEHQ0oPADUI
AQdDShAANQgBBENKEAAAB0NKHAA1CAEJA2oAAAAAVQgBAEYACAAABAgAAAYIAAAMCAAAgAgAAIQI
AACGCAAAxggAAOQIAADzAAAAAAAAAAAAAAAAvwAAAAAAAAAAAAAAALcAAAAAAAAAAAAAAACqAAAA
AAAAAAAAAAAAoAAAAAAAAAAAAAAAAGwAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAVAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACwAAFiQBSWYBAAAARyQAE6R4ABSkeAAA
CwAAFiQBSWYBAAAARyQAE6R4ABSkeAA0AAAWJAEXJAFJZgEAAAAI1hoAAYX/DSQAAAAAAAAAAAgB
AQAAAAAACAEBAAnWAgAAEtYKAAAA/wAAAP8AADTWBgABAQMAADTWBgABAgNsADTWBgABBAMAADTW
BgABCANsAAM0AGY0AAoAABYkAUlmAQAAABOkeAAUpFAADQAAFiQBSWYBAAAAAyQBYSQBE6R4ABSk
UAAABwAAFiQBSWYBAAAARyQANAAAFiQBFyQBSWYBAAAACNYaAAGF/w0kAAAAAAgBAQAIAQEAAAAA
AAgBAQAJ1gIAABLWCgAAAP8AAAD/AAA01gYAAQEDAAA01gYAAQIDbAA01gYAAQQDAAA01gYAAQgD
bAADNABmNAAACwAAFiQBSWYBAAAARyQAE6RQABSkKAAACOQIAADmCAAA6AgAAOoIAAAWCQAARAkA
ALoAAAAAAAAAAAAAAACrAAAAAAAAAAAAAAAAdwAAAAAAAAAAAAAAAGsAAAAAAAAAAAAAAABfAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACwAA
FiQBSWYBAAAARyQAE6Q8ABSkPAAACwAAFiQBSWYBAAAARyQAE6Q8ABSkPAA0AAAWJAEXJAFJZgEA
AAAI1hoAAYX/DSQAAAAAAAAAAAgBAQAEAQEACAEBAAnWAgAAEtYKAAAA/wAAAP8AADTWBgABAQMA
ADTWBgABAgNsADTWBgABBAMAADTWBgABCANsAAM0AGY0AAAOAAAWJAFJZgEAAAADJAFhJAFHJAAT
pCgAFKQoAEUAABYkARckAUlmAQAAAAjWMAAChf+6EQ0kAAAAAAAAAAAIAQEABAEBAAAAAAAAAAAA
AAAAAAAAAAAEAQEACAEBAAnWBAAAAAAS1hQAAAD/AAAA/wAAAAAA/wAAAP8AADTWBgABAQMAADTW
BgABAgNsADTWBgABBAMAADTWBgABCANsAAM0AWY0AQAFRAkAAEYJAAB4CQAAegkAAKAJAADWCQAA
2AkAAPAJAAAgCgAAugAAAAAAAAAAAAAAAK4AAAAAAAAAAAAAAAB6AAAAAAAAAAAAAAAAbgAAAAAA
AAAAAAAAAGIAAAAAAAAAAAAAAAC6AAAAAAAAAAAAAAAAVgAAAAAAAAAAAAAAAEoAAAAAAAAAAAAA
AAAAAAAAAAAAAAALAAAWJAFJZgEAAABHJAATpDwAFKQ8AAALAAAWJAFJZgEAAABHJAATpDwAFKQ8
AAALAAAWJAFJZgEAAABHJAATpDwAFKQ8AAALAAAWJAFJZgEAAABHJAATpFAAFKRQADQAABYkARck
AUlmAQAAAAjWGgABhf8NJAAAAAAEAQEACAEBAAQBAQAIAQEACdYCAAAS1goAAAD/AAAA/wAANNYG
AAEBAwAANNYGAAECA2sANNYGAAEEAwAANNYGAAEIA2sAAzQBZjQBAAsAABYkAUlmAQAAAEckABOk
PAAUpDwARQAAFiQBFyQBSWYBAAAACNYwAAKF/6gRDSQAAAAABAEBAAgBAQAEAQEAAAAAAAAAAAAE
AQEABAEBAAQBAQAIAQEACdYEAAAAABLWFAAAAP8AAAD/AAAAAAD/AAAA/wAANNYGAAEBAwAANNYG
AAECA2sANNYGAAEEAwAANNYGAAEIA2sAAzQBZjQBAAggCgAAIgoAACQKAAAmCgAAOAoAAFIKAABo
CgAAugAAAAAAAAAAAAAAAK4AAAAAAAAAAAAAAAB6AAAAAAAAAAAAAAAAaAAAAAAAAAAAAAAAAFkA
AAAAAAAAAAAAAABKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAA4AABYkAUlmAQAAAAMkAWEkAUckABOkKAAUpAAAAA4AABYkAUlmAQAAAAMkAWEk
AUckABOkoAAUpFAAABEAABYkAUlmAQAAAEckAF6EjgBdhAAAYIQAABOkUAAUpFAANAAAFiQBFyQB
SWYBAAAACNYaAAGF/w0kAAAAAAQBAQAIAQEAAAAAAAgBAQAJ1gIAABLWCgAAAP8AAAD/AAA01gYA
AQEDAAA01gYAAQIDawA01gYAAQQDAAA01gYAAQgDawADNAFmNAEACwAAFiQBSWYBAAAARyQAE6Q8
ABSkPABFAAAWJAEXJAFJZgEAAAAI1jAAAoX/qBENJAAAAAAEAQEACAEBAAQBAQAAAAAAAAAAAAQB
AQAEAQEABAEBAAgBAQAJ1gQAAAAAEtYUAAAA/wAAAP8AAAAAAP8AAAD/AAA01gYAAQEDAAA01gYA
AQIDawA01gYAAQQDAAA01gYAAQgDawADNAFmNAEABmgKAAByCgAAdAoAAK4KAACwCgAAsgoAALQK
AAC2CgAAzAoAAPAAAAAAAAAAAAAAAACJAAAAAAAAAAAAAAAAdwAAAAAAAAAAAAAAAGgAAAAAAAAA
AAAAAABdAAAAAAAAAAAAAAAAUgAAAAAAAAAAAAAAAEkAAAAAAAAAAAAAAABJAAAAAAAAAAAAAAAA
AAAAAAAACQAAFiQBSWYBAAAAAyQBYSQBAAoAABYkAUlmAQAAAAMkAWEkAUckAAAKAAAWJAFJZgEA
AAADJAFhJAFHJAAADgAAFiQBSWYBAAAAAyQBYSQBRyQAE6SgABSkUAAAEQAAFiQBSWYBAAAARyQA
XoSOAF2EAABghAAAE6RQABSkUABnAAAWJAEXJAFJZgEAAAAI1lwABIX/6Qn8FHUcDSQAAAAABAEB
AAgBAQAEAQEAAAAAAAAAAAAEAQEABAEBAAQBAQAAAAAAAAAAAAQBAQAEAQEABAEBAAAAAAAAAAAA
BAEBAAQBAQAEAQEACAEBAAnWCAAAAAAAAAAAEtYoAAAA/wAAAP8AAAAAAP8AAAD/AAAAAAD/AAAA
/wAAAAAA/wAAAP8AADTWBgABAQMAADTWBgABAgNrADTWBgABBAMAADTWBgABCANrAAM0AWY0AQAO
AAAWJAFJZgEAAAADJAFhJAFHJAATpCgAFKQAAAAIzAoAAM4KAABKCwAATAsAAE4LAABQCwAAUgsA
AMwLAACYAAAAAAAAAAAAAAAAhgAAAAAAAAAAAAAAAHcAAAAAAAAAAAAAAABsAAAAAAAAAAAAAAAA
YQAAAAAAAAAAAAAAAJgAAAAAAAAAAAAAAABPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAEQAAFiQBSWYBAAAARyQAXoSOAF2EAABghAAAE6RQABSkUAAACgAA
FiQBSWYBAAAAAyQBYSQBRyQAAAoAABYkAUlmAQAAAAMkAWEkAUckAAAOAAAWJAFJZgEAAAADJAFh
JAFHJAATpKAAFKRQAAARAAAWJAFJZgEAAABHJABehI4AXYQAAGCEAAATpFAAFKRQAGcAABYkARck
AUlmAQAAAAjWXAAEhf/pCfwUdRwNJAAAAAAEAQEACAEBAAQBAQAAAAAAAAAAAAQBAQAEAQEABAEB
AAAAAAAAAAAABAEBAAQBAQAEAQEAAAAAAAAAAAAEAQEABAEBAAQBAQAIAQEACdYIAAAAAAAAAAAS
1igAAAD/AAAA/wAAAAAA/wAAAP8AAAAAAP8AAAD/AAAAAAD/AAAA/wAANNYGAAEBAwAANNYGAAEC
A2sANNYGAAEEAwAANNYGAAEIA2sAAzQBZjQBAAfMCwAAzgsAANALAADSCwAA1AsAABYMAAAYDAAA
GgwAAPAAAAAAAAAAAAAAAADlAAAAAAAAAAAAAAAA2gAAAAAAAAAAAAAAAHMAAAAAAAAAAAAAAABh
AAAAAAAAAAAAAAAAUgAAAAAAAAAAAAAAAEMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAWJAFJ
ZgEAAAADJAFhJAFHJAATpCgAFKQAAAAOAAAWJAFJZgEAAAADJAFhJAFHJAATpKAAFKRQAAARAAAW
JAFJZgEAAABHJABehI4AXYQAAGCEAAATpFAAFKRQAGcAABYkARckAUlmAQAAAAjWXAAEhf/pCfwU
dRwNJAAAAAAEAQEACAEBAAQBAQAAAAAAAAAAAAQBAQAEAQEABAEBAAAAAAAAAAAABAEBAAQBAQAE
AQEAAAAAAAAAAAAEAQEABAEBAAQBAQAIAQEACdYIAAAAAAAAAAAS1igAAAD/AAAA/wAAAAAA/wAA
AP8AAAAAAP8AAAD/AAAAAAD/AAAA/wAANNYGAAEBAwAANNYGAAECA2sANNYGAAEEAwAANNYGAAEI
A2sAAzQBZjQBAAoAABYkAUlmAQAAAAMkAWEkAUckAAAKAAAWJAFJZgEAAAADJAFhJAFHJAAADgAA
FiQBSWYBAAAAAyQBYSQBRyQAE6SgABSkUAAABxoMAAAcDAAAHgwAAGoMAABsDAAAbgwAAHAMAABy
DAAA8AAAAAAAAAAAAAAAAIkAAAAAAAAAAAAAAAB3AAAAAAAAAAAAAAAAaAAAAAAAAAAAAAAAAFkA
AAAAAAAAAAAAAABKAAAAAAAAAAAAAAAAiQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAADgAAFiQBSWYBAAAAAyQBYSQBRyQAE6QoABSkAAAADgAAFiQBSWYBAAAAAyQBYSQBRyQA
E6QoABSkAAAADgAAFiQBSWYBAAAAAyQBYSQBRyQAE6SgABSkUAAAEQAAFiQBSWYBAAAARyQAXoSO
AF2EAABghAAAE6RQABSkUABnAAAWJAEXJAFJZgEAAAAI1lwABIX/6Qn8FHUcDSQAAAAAAAAAAAgB
AQAEAQEAAAAAAAAAAAAAAAAABAEBAAQBAQAAAAAAAAAAAAAAAAAEAQEABAEBAAAAAAAAAAAAAAAA
AAQBAQAEAQEACAEBAAnWCAAAAAAAAAAAEtYoAAAA/wAAAP8AAAAAAP8AAAD/AAAAAAD/AAAA/wAA
AAAA/wAAAP8AADTWBgABAQMAADTWBgABAgNrADTWBgABBAMAADTWBgABCANrAAM0AWY0AQAOAAAW
JAFJZgEAAAADJAFhJAFHJAATpCgAFKQAAAAHcgwAAL4MAADADAAAwgwAAMQMAADGDAAAIA0AAO0A
AAAAAAAAAAAAAADeAAAAAAAAAAAAAAAAzwAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAABZAAAAAAAA
AAAAAAAARwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAR
AAAWJAFJZgEAAABHJABehI4AXYQAAGCEAAATpFAAFKRQAGcAABYkARckAUlmAQAAAAjWXAAEhf/p
CfwUdRwNJAAAAAAAAAAACAEBAAQBAQAAAAAAAAAAAAAAAAAEAQEABAEBAAAAAAAAAAAAAAAAAAQB
AQAEAQEAAAAAAAAAAAAAAAAABAEBAAQBAQAIAQEACdYIAAAAAAAAAAAS1igAAAD/AAAA/wAAAAAA
/wAAAP8AAAAAAP8AAAD/AAAAAAD/AAAA/wAANNYGAAEBAwAANNYGAAECA2sANNYGAAEEAwAANNYG
AAEIA2sAAzQBZjQBAA4AABYkAUlmAQAAAAMkAWEkAUckABOkKAAUpAAAAA4AABYkAUlmAQAAAAMk
AWEkAUckABOkKAAUpAAAAA4AABYkAUlmAQAAAAMkAWEkAUckABOkoAAUpFAAABEAABYkAUlmAQAA
AEckAF6EjgBdhAAAYIQAABOkUAAUpFAAAAYgDQAAIg0AACQNAAAmDQAAKA0AAIYOAADwAAAAAAAA
AAAAAAAA4QAAAAAAAAAAAAAAANIAAAAAAAAAAAAAAABrAAAAAAAAAAAAAAAAWwAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAWJAFJZgEAAAANxgUAAWwB
AEckABOkUAAUpFAAZwAAFiQBFyQBSWYBAAAACNZcAASF/+kJ/BR1HA0kAAAAAAQBAQAIAQEAAAAA
AAAAAAAAAAAABAEBAAQBAQAAAAAAAAAAAAAAAAAEAQEABAEBAAAAAAAAAAAAAAAAAAQBAQAEAQEA
AAAAAAgBAQAJ1ggAAAAAAAAAABLWKAAAAP8AAAD/AAAAAAD/AAAA/wAAAAAA/wAAAP8AAAAAAP8A
AAD/AAA01gYAAQEDAAA01gYAAQIDawA01gYAAQQDAAA01gYAAQgDawADNAFmNAEADgAAFiQBSWYB
AAAAAyQBYSQBRyQAE6QoABSkAAAADgAAFiQBSWYBAAAAAyQBYSQBRyQAE6QoABSkAAAADgAAFiQB
SWYBAAAAAyQBYSQBRyQAE6SgABSkUAAABYYOAACIDgAAig4AAIwOAACODgAAwA4AAMIOAADEDgAA
xg4AAMgOAADKDgAAzA4AAM4OAADJAAAAAAAAAAAAAAAAvgAAAAAAAAAAAAAAALgAAAAAAAAAAAAA
AACEAAAAAAAAAAAAAAAAfgAAAAAAAAAAAAAAAHwAAAAAAAAAAAAAAAB6AAAAAAAAAAAAAAAAeAAA
AAAAAAAAAAAAAHYAAAAAAAAAAAAAAAB0AAAAAAAAAAAAAAAAcgAAAAAAAAAAAAAAAHAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAQAAAAEAAAABFwAAAQAAAAEWAAYWAA3GBgI5
EHIgADQAABYkARckAUlmAQAAAAjWGgABhf/vIwAAAAAAAAAAAAAAAAAAAAAAAAAACdYCAAAS1goA
AAD/AAAA/wAANNYGAAEBAwAANNYGAAECA2sANNYGAAEEAwAANNYGAAEIA2sAAzQAZjQABgAAFiQB
SWYBAAAAAAoAABYkAUlmAQAAAAMkAWEkAUckADYAABYkARckAUlmAQAAAAjWGgABhf8NJAAAAAAE
AQEACAEBAAQBAQAIAQEAB5SRAwnWAgAAEtYKAAAA/wAAAP8AADTWBgABAQMAADTWBgABAgNrADTW
BgABBAMAADTWBgABCANrAAM0AWY0AQAMzg4AANAOAADSDgAA1g4AANgOAAAmDwAAKA8AACoPAAAs
DwAA/QAAAAAAAAAAAAAAAPsAAAAAAAAAAAAAAAD2AAAAAAAAAAAAAAAA9AAAAAAAAAAAAAAAAO8A
AAAAAAAAAAAAAADtAAAAAAAAAAAAAAAA6wAAAAAAAAAAAAAAAOQAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYWAA3GBgI5EHIgADQAAQAAAAEAAAUDAAomAgtGAQAA
AQAABQEACiYAC0YBAAABAAAAAQAAAAg4AB+wgS4gsMVBIbCKBSKwigUXsKAMI5CGDRiwqQEkkI8C
MlAAADGQaAEwcAAAAAAzUAAAKDIADjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAFIAbwBvAHQAIABFAG4AdAByAHkAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWAAUA//////////8BAAAABgkCAAAAAADAAAAA
AAAARgAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAEARAAAAAAAAAQBDAG8AbQBwAE8AYgBqAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIAAgACAAAABAAAAP//
//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAagAAAAAAAAABAE8AbABl
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
CgACAP////8DAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAU
AAAAAAAAADEAVABhAGIAbABlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAOAAIA////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAwAAAIQOAAAAAAAABQBTAHUAbQBtAGEAcgB5AEkAbgBmAG8AcgBtAGEAdABpAG8A
bgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAgAFAAAABwAAAP////8AAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+AAAAGAEAAAAAAABXAG8AcgBkAEQAbwBjAHUAbQBlAG4A
dAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGgACAAYAAAD/////////
/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAA6KgAAAAAAAE8AYgBqAGUA
YwB0AFAAbwBvAGwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAW
AAEA////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/v///wAA
AAAAAAAABQBEAG8AYwB1AG0AZQBuAHQAUwB1AG0AbQBhAHIAeQBJAG4AZgBvAHIAbQBhAHQAaQBv
AG4AAAAAAAAAAAAAADgAAgD///////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAABDAAAAdAAAAAAAAAA=

------=_MIME_BOUNDARY_000_94493--



BODY2
my $header3 = <<'HEADER3';
1bVCqk-0001rd-7G-H
exim 93 93
<andrew@home.topdog-software.com>
1470294830 0
-helo_name fuzzylumpkins.local
-host_address 192.168.1.52.61162
-interface_address 192.168.1.14.25
-active_hostname ms2.home.topdog-software.com
-received_protocol esmtps
-aclc _n 1
0
-aclc _l 3
250
-aclm _av_scanner 32
clamd:/var/run/clamav/clamd.sock
-aclm 0 2
no
-body_linecount 20
-max_received_linelength 76
-host_lookup_failed
-tls_cipher TLS1.2:ECDHE_RSA_AES_256_GCM_SHA384:256
-tls_ourcert -----BEGIN CERTIFICATE-----\nMIIGRjCCBS6gAwIBAgISAyaEr1dYsVd/bDUKfZmQByDFMA0GCSqGSIb3DQEBCwUA\nMEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD\nExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0xNjA2MTgxNjAwMDBaFw0x\nNjA5MTYxNjAwMDBaMCoxKDAmBgNVBAMTH3NjYW5uZXIubGFiLnRvcGRvZy1zb2Z0\nd2FyZS5jb20wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCu9Xl/A28t\n3TeU/NkVQtAlioDOtEPqkOdslKviiKS/saQItq1ojlX/ohb37v+aW/74EiW2IjYd\nQwXa2sI1XjwLCHJ3PGQVpxMGhvvFW5lLfsBEi4lqjQdaIt7G/ZN3oAMJf078Hs28\nVMjKPvMx1HxwFmxcdeTwpjBOXa4F4/HqLcRp8JrOcwBbZMgQQxfZagfpmQ4XKMsC\nrXAL16KT6x+T0cLDxtLo32mc75hQZ1UhutWRNFI7O151pgS+cdNR77Y/FiRcfQ8y\nqz4NNIMQEuSy8UPtlHgw+mHrpjnYmuHf8ogchJMb3ZvdsQUX+xFL5a/VVtuMTYmk\nFdx7V0Guz7Y1YUzVDU9tsz96G0V3y0UaIOgAPUabBvUnsyhQ40Js7nR+/BZ34uzx\nFBLp9BSA5zhc3shslUN7WrV+3v9462mYKTrdjH3qwyaeh9d8HNM39O2yJmkkJvv/\npwevbLvqIRN3vCCBmlFi8qsgwOG08Zm/yiDOzFg5BjZVXw6ADI7sMUqlvxZx5whM\nOHnr1ua/GNpHRwTeXkGuQtvFAjqPmQAXZeSQTNuUpNrclosgEvgpJchAKnkqBRFd\nXpKqGbKlp8UQYg0AQJiIipXc06ZHiIrZQ4g+3cbr7uQUrkuFxti4bo4fpXOj4P6M\nkXfPnoAGqx+dpv85ZEMkLpCjVr3/hxzoLQIDAQABo4ICRDCCAkAwDgYDVR0PAQH/\nBAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8E\nAjAAMB0GA1UdDgQWBBR7b9MfNDC6QGMCDOdpv7W0QVUskjAfBgNVHSMEGDAWgBSo\nSmpjBH3duubRObemRWXv86jsoTBwBggrBgEFBQcBAQRkMGIwLwYIKwYBBQUHMAGG\nI2h0dHA6Ly9vY3NwLmludC14My5sZXRzZW5jcnlwdC5vcmcvMC8GCCsGAQUFBzAC\nhiNodHRwOi8vY2VydC5pbnQteDMubGV0c2VuY3J5cHQub3JnLzBOBgNVHREERzBF\ngiJwb3N0b2ZmaWNlLmxhYi50b3Bkb2ctc29mdHdhcmUuY29tgh9zY2FubmVyLmxh\nYi50b3Bkb2ctc29mdHdhcmUuY29tMIH+BgNVHSAEgfYwgfMwCAYGZ4EMAQIBMIHm\nBgsrBgEEAYLfEwEBATCB1jAmBggrBgEFBQcCARYaaHR0cDovL2Nwcy5sZXRzZW5j\ncnlwdC5vcmcwgasGCCsGAQUFBwICMIGeDIGbVGhpcyBDZXJ0aWZpY2F0ZSBtYXkg\nb25seSBiZSByZWxpZWQgdXBvbiBieSBSZWx5aW5nIFBhcnRpZXMgYW5kIG9ubHkg\naW4gYWNjb3JkYW5jZSB3aXRoIHRoZSBDZXJ0aWZpY2F0ZSBQb2xpY3kgZm91bmQg\nYXQgaHR0cHM6Ly9sZXRzZW5jcnlwdC5vcmcvcmVwb3NpdG9yeS8wDQYJKoZIhvcN\nAQELBQADggEBAC3CFdwbBbVbGGh4Lga1yF8GDVkkjE7twQmJI0oWfjX87J4axJIG\neLK+DGdI0ZuknpwsxxA6CBIdibS6X9beEOYaOHza8WLz7GW2zX2u5RuOuBq6bpkd\nvxA8iBdWPY63DH4tYVceo8dqmCrlbHtEA99pesvUcH3Uy2IlvlVRjdSk9t0m9+em\nMWeF9gOwYxgdPys3QUayfBzK/x+lltJjxisibtUbou2AYDTIiMCxjrRTyiYYctNR\nTRdVKV0nOjjgvsscIkFBKP6iwmzyH6DgOTsfkzZkTqlOVU0rrBMlWXlqmd+3Be1Q\nIzRqELgGN2T7+j8cY9mgKyYhzZ3GrH7HIac=\n-----END CERTIFICATE-----\n
XX
1
angel@home.topdog-software.com

318P Received: from [192.168.1.52] (helo=fuzzylumpkins.local)
    by postoffice.lab.topdog-software.com with esmtps (TLS1.2:ECDHE_RSA_AES_256_GCM_SHA384:256)
    (Baruwa 2.0)
    (envelope-from <andrew@home.topdog-software.com>)
    id 1bVCqk-0001rd-7G ret-id none;
    for angel@home.topdog-software.com; Thu, 04 Aug 2016 09:13:50 +0200
038  Date: Thu, 04 Aug 2016 09:13:52 +0200
035T To: angel@home.topdog-software.com
038F From: andrew@home.topdog-software.com
046  Subject: test Thu, 04 Aug 2016 09:13:52 +0200
057  X-Mailer: swaks v20130209.0 jetmore.org/john/code/swaks/
018  MIME-Version: 1.0
071  Content-Type: multipart/mixed; boundary="----=_MIME_BOUNDARY_000_5270"
049  X-Baruwa-Virus-Checks: bypassed smtp time checks
HEADER3
my $body3 = <<'BODY3';
1bVCqk-0001rd-7G-D
------=_MIME_BOUNDARY_000_5270
Content-Type: text/plain

This is a test mailing
------=_MIME_BOUNDARY_000_5270
Content-Type: application/octet-stream; name="ignore.txt.zip"
Content-Description: ignore.txt.zip
Content-Disposition: attachment; filename="ignore.txt.zip"
Content-Transfer-Encoding: BASE64

UEsDBBQACAAIAOJO60gAAAAAAAAAAAAAAAAKABAAaWdub3JlLnR4dFVYDADs6qJX11CDV/UBFABl
jLEOwjAQQ/f7lEq9SvwBlRgzwcIUXdIUoqa5KLm0gq+nFWVisZ9sy4omN/rgQB2AHAboq/8pGhJQ
l9sZG1D3A9DsVQf6cMuLy3owHZjgN/XRdoBhTZZ58q5sTEX0d1aEpEB8Sco8IleBxMPpKXODMidI
sxbW+w/0lOtK7dVSjC63zV+AQhkfb/gAUEsHCNqQup6LAAAAxgAAAFBLAQIVAxQACAAIAOJO60ja
kLqeiwAAAMYAAAAKAAwAAAAAAAAAAECkgQAAAABpZ25vcmUudHh0VVgIAOzqolfXUINXUEsFBgAA
AAABAAEARAAAANMAAAAAAA==

------=_MIME_BOUNDARY_000_5270--


BODY3

sub create_config {
    my ($from, $to, $path) = @_;
    open(FROM, '<', $from) or die "Could not open $from\n";
    open(TO,   '>', $to)   or die "Could not open $to\n";
    while (<FROM>) {
        unless (/PATH/) {
            print TO;
            next;
        }
        s/PATH/$path/;
        print TO;
    }
    close(FROM);
    close(TO);
}

sub make_test_dirs {
    remove_tree("$Bin/data/var/spool/exim/input",      {keep_root => 1});
    remove_tree("$Bin/data/var/spool/exim.in/input",   {keep_root => 1});
    remove_tree("$Bin/data/var/spool/baruwa/incoming", {keep_root => 1});
    foreach (@paths) {
        make_path($_, {mode => 0700}) unless (-d $_);
    }
    touch(@files) unless -f $files[0];
    unless (-f "$Bin/data/etc/mail/baruwa/virus.scanners.conf") {
        my $cp = File::NCopy->new(recursive => 1);
        $cp->copy("$Bin/../etc/mail/baruwa/*", "$Bin/data/etc/mail/baruwa/");
    }
    create_file("$Bin/data/var/spool/exim.in/input/1bUUOQ-0000g4-C7-H",
        $header1);
    create_file("$Bin/data/var/spool/exim.in/input/1bUUOQ-0000g4-C7-D", $body1);
    create_file("$Bin/data/var/spool/exim.in/input/1bUvRz-0001Mr-4W-H",
        $header2);
    create_file("$Bin/data/var/spool/exim.in/input/1bUvRz-0001Mr-4W-D", $body2);
    create_file("$Bin/data/var/spool/exim.in/input/1bVCqk-0001rd-7G-H",
        $header3);
    create_file("$Bin/data/var/spool/exim.in/input/1bVCqk-0001rd-7G-D", $body3);
}

sub create_file {
    my ($filename, $data) = @_;
    unless (-f "$filename") {
        open(FILE, '>', $filename) or die "Could not create file: $filename";
        print FILE $data;
        close(FILE);
    }
}
