#!/bin/sh
# -*- coding: utf-8 -*-
# vim: ai ts=4 sts=4 et sw=4
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# This file was forked from MailScanner in July 2016.
# Original author, and relevant copyright and licensing information is below:
# :author: Julian Field
# :copyright: Copyright (C) 2002  Julian Field
#
# esets-wrapper --	invoke ESET for use with Baruwa

ScanOptions=""
PackageDir=$1
shift
Prog=esets_scan

if [ "x$1" = "x-IsItInstalled" ]; then
  [ -x ${PackageDir}/$Prog ] && exit 0
  exit 1
fi

exec $PackageDir/$Prog $ScanOptions "$@"

