#!/bin/sh
# -*- coding: utf-8 -*-
# vim: ai ts=4 sts=4 et sw=4
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# This file was forked from MailScanner in July 2016.
# Original author, and relevant copyright and licensing information is below:
# :author: Julian Field
# :copyright: Copyright (C) 2002  Julian Field
#
# f-securewrapper --	invoke F-Secure AV for use with Baruwa
#

# Look to see what version we have got installed.
# The new (4.50) version sets the database directory in /etc/fsav.conf.
# So if we find it there then we are running the new version.

Root=$1
shift

# FSAV version 4.6x
FSAV_CONF=/etc/opt/f-secure/fssp/fssp.conf
if [ -f $FSAV_CONF ] && grep -i '^daemondatabasedirectory' $FSAV_CONF  >/dev/null
then
  PackageDir=$Root/bin
  ScanOptions="--riskware=on --scanexecutables=on --virus-action1=report --virus-action2=none --riskware-action1=report --riskware-action2=none --skiplarge=no --databasedirectory=/var/opt/f-secure/fssp/databases"
else
  # FSAV version 4.6x
  FSAV_CONF=/etc/opt/f-secure/fsav/fsav.conf
  if [ -f $FSAV_CONF ] && grep -i '^databasedirectory' $FSAV_CONF >/dev/null
  then
    PackageDir=$Root/bin
    ScanOptions=""
  else
    # FSAV version 4.5x
    FSAV_CONF=/etc/fsav.conf
    if [ -f $FSAV_CONF ] && grep -i '^databasedirectory' $FSAV_CONF  >/dev/null
    then
      # New version
      PackageDir=$Root/bin
      ScanOptions=""
    else
      # Old version
      PackageDir=/usr/local/fsav 
      # Use their local setting if it exists. Helps backward compatibility
      if [ -d "$Root" ]; then
        PackageDir=$Root
      fi
      # I'm only listing ones which we may find useful...
      #
      # The *required* options are passed to us by Baruwa
      # currently these are "--auto --dumb --archive" (2/1/02) -- nwp
      #
      ScanOptions=""
      #ScanOptions="$ScanOptions --archive" # scan archives
      #ScanOptions="$ScanOptions --dumb" # don't try to be smart about file types
      #ScanOptions="$ScanOptions --auto" # no prompts
      # Where to find signature files
      ScanOptions="$ScanOptions --databasedirectory $PackageDir"
    fi
  fi
fi

if [ "x$1" = "x-IsItInstalled" ]; then
  [ -x ${PackageDir}/fsav ] && exit 0
  exit 1
fi

exec ${PackageDir}/fsav $ScanOptions "$@"

