#!/bin/sh
# -*- coding: utf-8 -*-
# vim: ai ts=4 sts=4 et sw=4
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# This file was forked from MailScanner in July 2016.
# Original author, and relevant copyright and licensing information is below:
# :author: Julian Field
# :copyright: Copyright (C) 2002  Julian Field
#

#set -x

PackageDir=$1
shift

# Handle Sophos V5 and V4
if [ "x$1" = "x-IsItInstalled" ]; then
  [ -x ${PackageDir}/bin/savscan ] && exit 0
  [ -x ${PackageDir}/bin/sweep ] && exit 0
  exit 1
fi

# Handle Sophos V5
if [ -x ${PackageDir}/bin/savscan ]; then
  #SAV_IDE=${PackageDir}/lib/sav # This may not be needed
  #export SAV_IDE
  LANG=C
  export LANG
  exec ${PackageDir}/bin/savscan "$@"
  exit 1
fi

#
# All the rest of this is for Sophos V4 and below
#

# Check to see if Sophos is using the Sophos install directory,
# rather than the Baruwa Sophos update directory.
SAV_IDE=$PackageDir/ide
if [ \! -x ${PackageDir}/ide -a -x ${PackageDir}/sav ]; then
  SAV_IDE=$PackageDir/sav
fi

LD_LIBRARY_PATH=$PackageDir/lib
LANG=C
export SAV_IDE
export LD_LIBRARY_PATH
export LANG

exec ${PackageDir}/bin/sweep "$@"

